// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const INIT_LOGIN = 'INIT_LOGIN';
export const LOGOUT = 'LOGOUT';

// Inventory
export const ADD_INVENTORY_REQUEST = 'ADD_INVENTORY_REQUEST'
export const ADD_INVENTORY_SUCCESS = 'ADD_INVENTORY_SUCCESS'
export const ADD_INVENTORY_FAIL = 'ADD_INVENTORY_FAIL'

// Product
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL'

// User 
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'
export const DELETE_USER_DATA = 'DELETE_USER_DATA'

// Messages
export const CLEAN_MESSAGE = 'CLEAN_MESSAGE'
export const DEFAULT_TIMEOUT_MESSAGE = 10000