// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const INIT_LOGIN = 'INIT_LOGIN';
export const LOGOUT = 'LOGOUT';

//
export const ADD_INVENTORY_REQUEST = 'ADD_INVENTORY_REQUEST'
export const ADD_INVENTORY_SUCCESS = 'ADD_INVENTORY_SUCCESS'
export const ADD_INVENTORY_FAIL = 'ADD_INVENTORY_FAIL'

// Messages
export const CLEAN_MESSAGE = 'CLEAN_MESSAGE'
export const DEFAULT_TIMEOUT_MESSAGE = 10000